## Lecture 3

**Python & Jupyter Notebooks**

Ask students if everyone was able to download and run jupyter notebooks okay. If not, show them how to launch a notebook.

Go over:

1. What is Python?

2. What is a Jupyter notebook? How can it be used? 
    - What is a cell (code cell, markdown cell)
    - How does code run (Sequentially, one line at a time)
    - How is your python code output displayed
    

Ask students how the tutorial went and if there are any of the tutorials they'd like me to explain or go through. Give students time for each tutorial and go over each exercise after each tutorial.

https://www.learnpython.org/en/Welcome

Tutorials:
1. Hello, World!
2. Variables and Types
3. Lists
4. Basic Operators
5. Loops



### What is a numpy array?

The numpy array is very similar to a list (Explained in tutorial) but it has additional features.
    You can use built in methods that are available in numpy like sort
    
    Example:
    
    

In [1]:
import numpy as np
#https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html

In [2]:
myNumpyArray = np.array([5, 2, -8, 100, .3])
print(myNumpyArray)

[  5.    2.   -8.  100.    0.3]


In [9]:
sortedArray = np.sort(myNumpyArray)
print(sortedArray)

[ -8.    0.3   2.    5.  100. ]


In [4]:
#To get the smallest take the first k elements from you numpy array
k = 3
kSmallest = sortedArray[0:k]
print(kSmallest)

[-8.   0.3  2. ]


### Exercise 1:
Calculate the distance between 2 (2-D) points. You need to do this using the Euclidean distance formula.

point1: (8,5)

point2: (5,9)



#### Solution:

In [5]:
dist = ((8-5)**2 + (5-9)**2)**(1/2)
print(dist)

5.0


### Exercise 2:

Given the numbers: [15, 20, 5, 22, 60, 35, 30, 18], sort them from smallest to largest and print out the k smallest, where k = 1,2,3?

#### Solution:

In [6]:
myArray = np.array([15, 20, 5, 22, 60, 35, 30, 18])
sorted = np.sort(myArray)

kSmallest = sorted[0:1]
print(kSmallest)

kSmallest = sorted[0:2]
print(kSmallest)

kSmallest = sorted[0:3]
print(kSmallest)


[5]
[ 5 15]
[ 5 15 18]


### Exercise 3:

Given a numpy array of training data, use a for loop to subtract each element of the training data by a test data point. 

trainingData = np.array([15, 20, 5, 22, 60, 35, 30, 18])

testDataPoint = 12

#### Solution:

In [7]:
trainingData = np.array([15, 20, 5, 22, 60, 35, 30, 18])
testDataPoint = 12

for i in range(np.size(trainingData)):
    element = trainingData[i]
    
    print(element - testDataPoint)
    
print(trainingData - testDataPoint)

3
8
-7
10
48
23
18
6
[ 3  8 -7 10 48 23 18  6]


** Coding basics **

Go over: 

1. Comments in code

2. Functions, why they are useful

3. Debugging code
    - Looking at errors
        - Syntax - how the code is written
        - Run time - occurs when the code is running
    - Looking at variables
        - printing the values of variables while code is running can be very useful
    - Write one line of code at a time
        - test the code to make sure it is doing what you want
